import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-900`}
      >
        {/* Header Component */}
        <Header />

        {/* Main Content */}
        <main className="container mx-auto min-h-screen p-4">{children}</main>

        {/* Footer */}
        <footer className="bg-white text-center py-4 shadow-md">
          © {new Date().getFullYear()} My Next.js App. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
